# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               coilly blog
tagline:             "web publisher"
description:         '부지런히 공부하고 노는게 목표
                        <br>2018~ <br> 네이버 블로그 <a href="https://blog.naver.com/c0illy">@c0illy</a>'
url:                  "https://coilly.github.io"
baseurl:             ''
paginate:            5

navigation:
- title: Home
  url: /index.html
- title: About
  url: /about
- title: Category
  url: /category
- title: Contact
  url: /contact

# About/contact
author:
  name:              Hyejin Kim
  url:               https://www.instagram.com/h_jin_1005/
  email:             jin03111@gmail.com

# Custom vars
version:             1.0.0
