# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               coilly blog
tagline:             "web publisher"
description:         '살기위해 공부함
                        <br>2017.12~ <br>일상담긴 네이버 블로그 운영중<br><a href="https://blog.naver.com/c0illy">@c0illy</a>'
url:                  "https://coilly.github.io"
baseurl:              ""
paginate:            5

category_dir: category/

#google analytics
google_analytics: UA-157465953-2

# About/contact
author:
  name:              Hyejin Kim
  url:               https://www.instagram.com/h_jin_1005/
  email:             jin03111@gmail.com

# Custom vars
version:             1.0.0
